update ubuntu for redis 8

diff --git a/Dockerfile-ubuntu b/Dockerfile-ubuntu
--- a/Dockerfile-ubuntu
+++ b/Dockerfile-ubuntu
@@ -1,10 +1,59 @@
 ARG OSV
+
+FROM alpine:latest AS downloader
+ARG TARGETARCH
+
+RUN apk add --no-cache wget tar
+
+WORKDIR /tmp
+
+# install cmake-3.31.7
+# needed by redis-8.x
+ENV CMV_MAIN=3.31
+ENV CMV_MINI=7
+ENV CM_URL="https://github.com/Kitware/CMake/releases/download"
+RUN case "${TARGETARCH}" in \
+    "amd64") \
+        wget -O install.sh ${CM_URL}/v${CMV_MAIN}.${CMV_MINI}/cmake-${CMV_MAIN}.${CMV_MINI}-linux-x86_64.sh ;; \
+    "arm64") \
+        wget -O install.sh ${CM_URL}/v${CMV_MAIN}.${CMV_MINI}/cmake-${CMV_MAIN}.${CMV_MINI}-linux-aarch64.sh ;; \
+    *) echo "ERROR: Unsupported arch"; exit 1 ;; \
+    esac && \
+    mkdir /tmp/cmake && \
+    /bin/sh /tmp/install.sh --prefix=/tmp/cmake --exclude-subdir
+
 FROM ubuntu:${OSV}
+ENV CMV_MAIN=3.31
+COPY --from=downloader /tmp/cmake/bin/* /usr/bin/
+COPY --from=downloader /tmp/cmake/share/cmake-${CMV_MAIN} /usr/share/cmake-${CMV_MAIN}
 
 CMD ["bash"]
 RUN apt-get update \
-    && apt-get install gcc make libssl-dev libsystemd-dev tcl tcl-tls -y \
-    && apt-get install --no-install-recommends pkg-config -y \
+    && apt-get install -y --no-install-recommends \
+        ca-certificates \
+        wget \
+        dpkg-dev \
+        gcc \
+        g++ \
+        libc6-dev \
+        libssl-dev \
+        make \
+        git \
+        python3 \
+        python3-pip \
+        python3-venv \
+        python3-dev \
+        unzip \
+        rsync \
+        clang \
+        automake \
+        autoconf \
+        libtool \
+        pkg-config \
+        libsystemd-dev \
+        # tcl for make test
+        tcl \
+        tcl-tls \
     && mkdir /workspace
 
 VOLUME [ "/workspace" ]
